SELECT ZIP, DAYCHAR, MAX(CNT) AS MAXSTOP
FROM
(
SELECT ADDRESS.C_ADDRESS_ZIPCODE AS ZIP, to_char(POINT.C_ACTUALARRIVAL, 'DAY') AS DAYCHAR, COUNT(*) AS CNT
FROM T_TOURMGMT_TOUR TOUR, T_TOURMGMT_TOURPOINT POINT,  T_ORGLOC_LOCATION LOC, T_ADDRESSMGMT_PADDRESS ADDRESS
WHERE POINT.FK_TOUR=TOUR.C_ID AND 
      LOC.FK_ADDRESS = ADDRESS.C_ID AND 
      POINT.FK_LOCATION = LOC.C_ID AND
      TOUR.C_ISACTUAL=1 
GROUP BY ADDRESS.C_ADDRESS_ZIPCODE, to_char(POINT.C_ACTUALARRIVAL, 'DAY')
ORDER BY CNT DESC
)
GROUP BY ZIP, DAYCHAR
ORDER BY MAX(CNT) DESC
